### ISSUE TITLE
Assignment operator is used in filter instead of equality operator

### ISSUE THREAD

**Issue by Ge0dude** [Affirm/shparkley#3]
I believe the line
`row = dataset.filter(dataset.row_id = 'xxxx').rdd.first()`
should instead use the equality operator like below
`row = dataset.filter(dataset.row_id == 'xxxx').rdd.first()`

**Comment by ijoseph** [comment]
Just added this fix to [my PR](https://github.com/Affirm/shparkley/pull/2) where I'm messing around with the readme anyhow.
